services:
  Nitsan\MobileCompany\Command\DeleteOldRecordsCommand:
    tags:
      - name: console.command
        command: 'mobilecompany:deleteoldrecords'
        description: 'Deletes old mobilecompany records.'
        schedulable: true